export const data = [
  {
    id: 'mx',
    name: 'MX',
    description: 'Математичне очікування',
    value: 240,
    min: 0,
    step: 1,
    max: 500,
  },
  {
    id: 'xti',
    name: 'Xti',
    description: 'Значення параметру на і-му циклі вимірювання',
    value: 250,
    min: 0,
    step: 1,
    max: 500,
  },
  {
    id: 'dx',
    name: 'Dx',
    description: 'Дисперсія',
    value: 32,
    min: 1,
    step: 1,
    max: 100,
  },
  {
    id: 't0',
    name: 't0',
    description: 'Тривалість циклу tц=τ0 (пері од опитування датчика)',
    value: 7,
    min: 1,
    step: 1,
    max: 100,
  },
  {
    id: 't',
    name: 't',
    description: 'Час затухання авто- кореляційної функції ',
    value: 18,
    min: 1,
    step: 1,
    max: 100,
  },
  {
    id: 'k',
    name: 'K',
    description: 'Параметр К',
    value: 1.5,
    min: 1,
    step: 1,
    max: 100,
  },
  {
    id: 'multiply',
    name: 'τ (коефіцієнт)',
    description: 'Період прогнозу, t (момент часу, в котрий необхідно визначити величину)',
    value: 0.55,
    min: 0,
    step: 0.05,
    max: 1,
  },
]