export const data = [
  {
    id: 'x1',
    name: '~x1',
    description: 'x1',
    value: 12,
    min: 0,
    step: 1,
    max: 100,
  },
  {
    id: 'x2',
    name: '~x2',
    description: 'x2',
    value: 10,
    min: 0,
    step: 1,
    max: 100,
  },
  {
    id: 'x3',
    name: '~x3',
    description: 'x3',
    value: 14,
    min: 0,
    step: 1,
    max: 100,
  },
  {
    id: 'x4',
    name: '~x4',
    description: 'x4',
    value: 34.2,
    min: 0,
    step: 1,
    max: 100,
  },
  {
    id: 'l',
    name: 'l*',
    description: 'l',
    value: 1.6,
    min: 0,
    step: 0.1,
    max: 100,
  },
  {
    id: 'delta_x',
    name: '~delta_x',
    description: 'Дельта x1, x2, x3',
    value: 0.45,
    min: 0,
    step: 0.05,
    max: 10,
  },
  {
    id: 'delta_x4',
    name: '~delta_x4',
    description: 'Дельта x4',
    value: 0.65,
    min: 0,
    step: 0.05,
    max: 10,
  }, 
  {
    id: 'sigma1',
    name: 'sigma1',
    description: 'Сигма x1',
    value: 0.3,
    min: 0,
    step: 0.05,
    max: 10,
  },
  {
    id: 'sigma2',
    name: 'sigma2',
    description: 'Сигма x2',
    value: 0.2,
    min: 0,
    step: 0.05,
    max: 10,
  },
  {
    id: 'sigma3',
    name: 'sigma3',
    description: 'Сигма x3',
    value: 0.36,
    min: 0,
    step: 0.05,
    max: 10,
  },
  {
    id: 'sigma4',
    name: 'sigma4',
    description: 'Сигма x4',
    value: 0.34,
    min: 0,
    step: 0.05,
    max: 10,
  }
 
]